get:
  summary: Get Sub Account Settings
  description: Get information about sub account settings.
  operationId: GetSubAccountSettings
  tags:
    - Sub Accounts
  parameters:
    - $ref: ../components/parameters/id-path.yaml
    - $ref: ../components/parameters/authorization-header.yaml
  responses:
    '200':
      description: Successfully get sub account settings
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../components/schemas/Envelope.yaml
              - properties:
                  type:
                    example: sub_account_settings
                  data:
                    $ref: ../components/schemas/SubAccountSettings.yaml
