import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Autogenerated sidebar for the Web Components docs plugin instance
const sidebars: SidebarsConfig = {
  wcSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
