post:
  description: |
    Received for the following events: application_fee_rate.created, application_fee_rate.updated
  tags:
    - Events
  operationId: applicationFeeRateEvent
  summary: Application Fee Rates
  requestBody:
    content:
      application/json:
        schema:
          allOf:
            - $ref: ../components/schemas/Event.yaml
            - properties:
                data:
                  $ref: ../components/schemas/ApplicationFeeRate.yaml
  responses:
    "200":
      description: Return a 200 status to indicate that the data was received successfully. You must respond within 5 seconds.